export const ADD_TODO = "ADD_TODO";
export const LOAD_TODO = "LOAD_TODO";
export const LOAD_TODO_SUCCESS="LOAD_TODO_SUCCESS";
export const LOAD_TODO_FAIL="LOAD_TODO_FAIL";
export const REMOVE_TODO = "REMOVE_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
export const COMPLETE_TODO_FAIL = "COMPLETE_TODO_FAIL";


export const ADD_TODO_SUCCES= "ADD_TODO_SUCCES";
export const ADD_TODO_FAIL= "ADD_TODO_FAIL";
export const REMOVE_TODO_SUCCESS="REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAIL="REMOVE_TODO_FAIL";